language: node_js

node_js:
  - "10"

notifications:
  email:
    - josh.rossi@alphapoint.com

before_script:

script:
  - npm run build
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master