const permissions = [
  'AddUserAffiliateTag',
  'AddUserAPIKey',
  'Authenticate2FA',
  'AuthenticateUser',
  'CancelAllOrders',
  'CancelOrder',
  'CancelUserReport',
  'CreateDepositTicket',
  'CreateWithdrawTicket',
  'Disable2FA',
  'EnableGoogle2FA',
  'GenerateTradeActivityReport',
  'GenerateTransactionActivityReport',
  'GenerateTreasuryActivityReport',
  'GetAccountInfo',
  'GetAccountPositions',
  'GetAccountTrades',
  'GetDepositInfo',
  'GetDepositRequestInfoTemplate',
  'GetDepositTickets',
  'GetInstruments',
  'GetOpenOrders',
  'GetOpenTradeReports',
  'GetOrderFee',
  'GetProducts',
  'GetTransfers',
  'GetUserAccounts',
  'GetUserAffiliateCount',
  'GetUserAffiliateTag',
  'GetUserAPIKeys',
  'GetUserConfig',
  'GetUserInfo',
  'GetUserPermissions',
  'GetUserReportTickets',
  'GetWithdrawFee',
  'GetWithdrawTemplate',
  'GetWithdrawTemplateTypes',
  'GetWithdrawTickets',
  'LogOut',
  'RegisterNewUser',
  'RemoveUserAPIKey',
  'RequestTransferFunds',
  'ResendVerificationEmail',
  'ResetPassword',
  'ScheduleTradeActivityReport',
  'ScheduleTransactionActivityReport',
  'ScheduleTreasuryActivityReport',
  'SendOrder',
  'SetUserConfig',
  'SetUserInfo',
  'SubmitBlockTrade',
  'SubscribeAccountEvents',
  'SubscribeLevel1',
  'SubscribeLevel2',
  'SubscribeTicker',
  'SubscribeTrades',
  'TransferFunds
  'UnSubscribeLevel1',
  'UnsubscribeLevel2',
  'UnSubscribeTicker',
  'UnSubscribeTrades',
  'ValidateUserRegistration',
  'WebAuthenticateUser'
];

const permissionsToRemove = [
  'SUPERUSER',
  'AdminUI',
  'UserOperator',
  'Trading',
  'Withdraw',
  'Deposit',
  'AccountOperator',
  'Remarketer'
];

const permissionsToAdd = ['RegisterNewUser'];

export const endpoints = [
  ...permissions.filter(x => !permissionsToRemove.includes(x)),
  ...permissionsToAdd
];
